**Lesson** 2.1

### Exercise

A. Create an ndarry object (A) with any values from 1 to 100 in a nested Python List. You can choose your range from the given values (1-100).

* Given that A is an ndarray object, many functionalities in numpy could be accessed by:
    + Make sure to explain each line of codes that you have created.

1. Using a property of the ndarray object
      - e.g. `A.shape`
2. Using a method of the ndarray object
      - e.g. `A.max()`
3. Using a numpy function and passing an ndarray
     - e.g. `np.max(A)`

B. Create a 5x5 integer-array filled with ones.
* Check its shape, size, and number of dimensions. Explain briefly the codes you have created by writing a comment beside the code.

C. Create an array of values from -5 to + 5. Multiply each value with 2. Print the resulting array.

**A.**

In [ ]:
import numpy as np

nested_list = [[i for i in range(1, 10)] for i in range(9)]

A = np.array(nested_list)

#1. Using a property of the ndarray object
print("Shape of A:", A.shape) #A.shape returns a tuple with each index having the number of corresponding elements. It indicates that A has 9 rows and 9 columns.

#2. Using a method of the ndarray object
max_value = A.max() #A.max() is a method that returns the maximum value in the ndarray A.
print("Maximum value in A:", max_value)  # To display the maximum number which is 9.

#3. Using a numpy function and passing an ndarray
min_value = np.min(A) #np.min(A) is a numpy function that returns the minimum value in the ndarray A.
print("Minimum value in A:", min_value) #To display the minimum number which is 1.


Shape of A: (9, 9)
Maximum value in A: 9
Minimum value in A: 1


**B.**

In [ ]:
import numpy as np

ones_array = np.ones((5, 5), dtype=int)

print("Shape of the array:", ones_array.shape) #The shape property of the array returns a tuple representing the dimensions of the array. It's (5, 5) indicating the array has 5 rows and 5 columns.

print("Size of the array:", ones_array.size) #The size property of the array returns the total number of elements in the array. For a 5x5 array, it will be 5*5 = 25.

print("Number of dimensions:", ones_array.ndim) #The ndim property of the array returns the number of dimensions (axes) of the array. It displays 2.



Shape of the array: (5, 5)
Size of the array: 25
Number of dimensions: 2


**C.**

In [ ]:
import numpy as np

original_array = np.arange(-5, 6)

resulting_array = original_array * 2 # This line of code multiply each value by 2.

print("Resulting array:", resulting_array) # Print the resulting array.


Resulting array: [-10  -8  -6  -4  -2   0   2   4   6   8  10]


**Lesson 2.2**

### Exercise

A. Choose the values from the range of numbers 1 to 100.
1. Create an array with 30 values within the range of numbers given. You can choose your own start value and stop value. However, the incrementing value will be 2.
   * Explain what is the result briefly by writing a comment before the code.
2. Multiply the resulting array with 3. Print the result.

In [ ]:
import numpy as np

# This line of code is an array with 30 values within the range of numbers 1 to 100, incrementing by 2. This generates an array starting from 10 up to 70 with a step size of 2.
array_30_values = np.arange(5, 75, 2)

#Displaying the resulting array
print("Array with 30 values within the range of numbers 1 to 100, incrementing by 2:")
print(array_30_values)

Array with 30 values within the range of numbers 1 to 100, incrementing by 2:
[ 5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51
 53 55 57 59 61 63 65 67 69 71 73]


### Exercise

A. Create a four-dimensional array of random integers in the interval [0, 12]. Print the result.
1. Get the dimensions, shape, and size.
    * Explain what is the result briefly by writing a comment before the code.

B. Get the maximum number for each dimensions and display it.
   * Explain what is the result briefly by writing a comment before the code.

C. Multipy each array with 4. What is its result?
    * Write a brief explanation on the multiplication process.


**A.**

In [ ]:
import numpy as np

# I created a four-dimensional array of random integers in the interval [0, 12].
four_dim_array = np.random.randint(0, 13, size=(3, 4, 2, 5))

# Print dimensions, shape, and size of the array
print("Dimensions of the array:", four_dim_array.ndim)
print("Shape of the array:", four_dim_array.shape)
print("Size of the array:", four_dim_array.size)


Dimensions of the array: 4
Shape of the array: (3, 4, 2, 5)
Size of the array: 120


**B.**

In [ ]:
# Getting the maximum number for each dimension and display the maximum number which is 12.
max_per_dimension = np.amax(four_dim_array, axis=(0, 1, 2, 3))
print("Maximum number for each dimension:", max_per_dimension)


Maximum number for each dimension: 12


**C.**

In [ ]:
# Multiplied each array element by 4 resulting in a new array where each value is four times the original value.
multiplied_array = four_dim_array * 4
print(multiplied_array)


[[[[ 4 28 28 16 16]
   [36 48 48 48  4]]

  [[ 8 48 12 28  0]
   [36 24 24 40  8]]

  [[ 4  8 12 40 16]
   [24 44 24 44 20]]

  [[44 32  4 20  0]
   [40 28 20 44 28]]]


 [[[12 24 32  4 24]
   [20 44 36  4 12]]

  [[ 4  0 28 12 36]
   [44 40 12  4  0]]

  [[32 36 44  8 48]
   [32 28 48 36 24]]

  [[28  4 20 48 16]
   [20  8 28 32 16]]]


 [[[40  0 16 44 16]
   [28 44 24 20  8]]

  [[ 4 48  8 12 48]
   [ 8 20 32 16  4]]

  [[24 16 48 32  8]
   [ 8 20 16  8 40]]

  [[12  8 40  0 12]
   [24 40 36 44  4]]]]
